# Generated by Django 5.2 on 2025-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingStatus',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('current_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('escalation_note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
