# Generated by Django 5.2 on 2025-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('escalation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('assigned_to', models.CharField(max_length=100)),
                ('status', models.CharField(default='open', max_length=20)),
                ('customer_id', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
