# Generated by Django 5.2 on 2025-04-24 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_care', '0002_escalation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolveIssue',
            fields=[
                ('escalation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('resolution_type', models.EmailField(max_length=254)),
                ('resolution_note', models.CharField(max_length=100)),
                ('notify_customer', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
