# Generated by Django 5.2 on 2025-04-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeStaffMember',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auction.user')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRepresentative',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auction.user')),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auction.user')),
                ('anonymize', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('desc_1', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_2', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_3', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.subcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('initial_price', models.IntegerField()),
                ('increment_price', models.IntegerField()),
                ('minimum_price', models.IntegerField(blank=True, null=True)),
                ('curr_price', models.IntegerField(blank=True, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.item')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.subcategory')),
                ('curr_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='auction.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.item')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.subcategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ques_text', models.CharField(max_length=500)),
                ('ans_text', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('timestamp_asked', models.DateTimeField()),
                ('timestamp_resolved', models.DateTimeField(blank=True, null=True)),
                ('customer_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.customerrepresentative')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('upper_limit', models.IntegerField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(max_length=3000)),
                ('end_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.enduser')),
            ],
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['cat_id', 'subcat_id'], name='auction_sub_cat_id__9af74e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('cat_id', 'subcat_id')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user_id', 'item_id', 'subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_id', 'subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='autobid',
            unique_together={('user_id', 'auction_id')},
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('end_user_id', 'message')},
        ),
    ]
