# Generated by Django 5.2 on 2025-04-25 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=50)),
                ('buyingPrice', models.IntegerField()),
                ('purchasedBy', models.CharField(max_length=255)),
                ('yardLocation', models.IntegerField()),
                ('auctionSetting', models.IntegerField()),
                ('bidNumber', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('transComment', models.CharField(max_length=100)),
                ('dataSource', models.CharField(max_length=255)),
                ('model', models.IntegerField()),
                ('chassisNo', models.CharField(max_length=50)),
                ('requestedBy', models.CharField(max_length=100)),
                ('yardDate', models.CharField(max_length=50)),
                ('auctionCharges', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('auctionSheet', models.FileField(blank=True, null=True, upload_to='auction_sheets/primary/')),
                ('auctionSheet2', models.FileField(blank=True, null=True, upload_to='auction_sheets/tertiary/')),
                ('requestedReason', models.CharField(max_length=255)),
                ('stockNumber', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('defaultFobPrice', models.CharField(max_length=255)),
                ('customerName', models.IntegerField()),
                ('transportCompany', models.CharField(max_length=50)),
                ('auctionName', models.CharField(max_length=100)),
                ('firstRegYear', models.CharField(max_length=100)),
                ('auctionSheet1', models.FileField(blank=True, null=True, upload_to='auction_sheets/secondary/')),
                ('exteriorColor', models.IntegerField()),
                ('shakenDate', models.CharField(max_length=50)),
                ('checkSpareKey', models.BooleanField(default=False)),
                ('checkSdCard', models.BooleanField(default=False)),
                ('removeTheHardCopyOfAuctionSheet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
