# Generated by Django 5.2 on 2025-04-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotation',
            new_name='greenpaper',
        ),
    ]
