# Generated by Django 5.2 on 2025-04-25 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('additional_specifications', models.CharField(max_length=255)),
                ('engine_number', models.IntegerField()),
                ('manufacturing_year', models.IntegerField()),
                ('variant', models.CharField(max_length=255)),
                ('fob_price', models.CharField(max_length=100)),
                ('cif_price', models.CharField(max_length=100)),
                ('shipping_port', models.CharField(max_length=255)),
                ('dilivery_time', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
