# Generated by Django 5.2 on 2025-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_quotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
